repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff is the lightning-fast linter & formatter that replaces flake8, isort, and black
    rev: v0.3.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
